### ISSUE TITLE
Fix InvalidPluginException occurring w/ older versions of Java Runtime.

### ISSUE THREAD

**Issue by dmccoystephenson** [dmccoystephenson/Medieval-Factions#1284]
[06:34:00] [Server thread/ERROR]: Could not load 'plugins/Medieval-Factions-4.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: dansplugins/factionsystem/MedievalFactions has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:332) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by dmccoystephenson** [comment]
It should be noted that I ran into this error on 1.16.5.

**Comment by VoChiDanh** [comment]
use java 16 and add `-DPaper.IgnoreJavaVersion=true` in cmd to run server. It will be ignore java version and run plugins

**Comment by VoChiDanh** [comment]
i dont sure about spigot, i tried with paper and it work

**Comment by Mr-Deej** [comment]
Spigot does not have a similar start up parameter only these [https://www.spigotmc.org/wiki/start-up-parameters/](https://www.spigotmc.org/wiki/start-up-parameters/)

**Comment by dmccoystephenson** [comment]
I'm not sure what version of java I used to compile the plugin. Do you think that using java 16 will result in less issues? @VoChiDanh

**Comment by VoChiDanh** [comment]
> I'm not sure what version of java I used to compile the plugin. Do you think that using java 16 will result in less issues? @VoChiDanh

I think it will be fine, but it would be better to ask to use paper because spigot can't skip the java check

**Comment by VoChiDanh** [comment]
@dmccoystephenson i think we can close this. We back to java 8 and fixed error when compile on java 8. Now we can run on all java version

**Comment by dmccoystephenson** [comment]
Sounds good, thanks! @VoChiDanh
