### ISSUE TITLE
Fix some players running into an internal error upon death.

### ISSUE THREAD

**Issue by dmccoystephenson** [dmccoystephenson/Medieval-Factions#1292]

**Comment by Mr-Deej** [comment]
Was this the error you were talking about in discord?
```
[22:12:59 ERROR]: Could not pass event EntityDamageByEntityEvent to MedievalFactions v4.5.1
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player1" is null
	at dansplugins.factionsystem.eventhandlers.helper.RelationChecker.getFactionIndices(RelationChecker.java:46) ~[Medieval-Factions-4.5.1.jar:?]
	at dansplugins.factionsystem.eventhandlers.helper.RelationChecker.arePlayersInSameFaction(RelationChecker.java:26) ~[Medieval-Factions-4.5.1.jar:?]
	at dansplugins.factionsystem.eventhandlers.DamageHandler.handleIfFriendlyFire(DamageHandler.java:160) ~[Medieval-Factions-4.5.1.jar:?]
	at dansplugins.factionsystem.eventhandlers.DamageHandler.handlePlayerVersusPlayer(DamageHandler.java:52) ~[Medieval-Factions-4.5.1.jar:?]
	at dansplugins.factionsystem.eventhandlers.DamageHandler.handle(DamageHandler.java:39) ~[Medieval-Factions-4.5.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1522]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1152) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1010) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:963) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1186) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2123) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1055) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1384) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:962) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1062) ~[?:?]
	at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1630) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:400) ~[?:?]
	at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:152) ~[?:?]
	at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:144) ~[?:?]
	at net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[?:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:155) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:146) ~[?:?]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:898) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3343) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:665) ~[?:?]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:304) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2993) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:427) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:297) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1216) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:698) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:676) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1635) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1522]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by dmccoystephenson** [comment]
I'm not sure because I've yet to see it myself but that definitely looks like it could be related @Mr-Deej

**Comment by koenderey** [comment]
Don't think that of mr-deej only applies to deaths of players.
We are getting a similar error in our server when nobody dies

02.02 22:40:58 [Server] Server thread/ERROR Could not pass event EntityDamageByEntityEvent to MedievalFactions v4.5
02.02 22:40:58 [Server] INFO org.bukkit.event.EventException: null
02.02 22:40:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
02.02 22:40:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
02.02 22:40:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
02.02 22:40:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
02.02 22:40:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:901) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:855) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1068) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:1974) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:975) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1325) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:882) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:928) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.EntityInsentient.z(EntityInsentient.java:1538) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.monster.EntityZombie.z(EntityZombie.java:346) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.a(SourceFile:152) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.e(SourceFile:144) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.ai.goal.PathfinderGoalZombieAttack.e(SourceFile:28) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.ai.goal.PathfinderGoalWrapped.e(SourceFile:65) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.a(SourceFile:119) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.b(SourceFile:110) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.EntityInsentient.eE(EntityInsentient.java:824) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.EntityLiving.w_(EntityLiving.java:3077) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.EntityInsentient.w_(EntityInsentient.java:615) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.monster.EntityMonster.w_(SourceFile:43) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.monster.EntityZombie.w_(EntityZombie.java:263) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2806) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.EntityInsentient.k(EntityInsentient.java:383) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.entity.monster.EntityZombie.k(EntityZombie.java:233) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.level.WorldServer.a(WorldServer.java:801) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.level.World.a(World.java:702) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.level.WorldServer.lambda$9(WorldServer.java:398) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.level.WorldServer.a(WorldServer.java:378) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1300) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3409-Spigot-862678e-30b4043]
02.02 22:40:58 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
02.02 22:40:58 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by Mr-Deej** [comment]
@koenderey there appears to be like 4-5 lines missing from the bottom of this error the part that tells us which class and where in it

**Comment by koenderey** [comment]
There are no more lines after it. 
I have 2 examples from today

https://pastebin.com/q3By2BML

**Comment by dmccoystephenson** [comment]
This pull request should have resolved this.
https://github.com/dmccoystephenson/Medieval-Factions/pull/1335
