### ISSUE TITLE
DamageHandler Bug

### ISSUE THREAD

**Issue by Randall-Rut** [dmccoystephenson/Medieval-Factions#1332]
**Describe the bug**
Sale cada cierto tiempo en la consola, en el juego no se nota pero si hay spam en la consola.

---
**To Reproduce**
Solo instalar el plugin

---
**Expected behavior**
que funcione bien sin errores en consola xd

---
**Screenshots or Logs**
[02:51:41 ERROR]: Could not pass event EntityDamageByEntityEvent to MedievalFactions v4.5.1
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player1" is null
        at dansplugins.factionsystem.eventhandlers.helper.RelationChecker.getFactionIndices(RelationChecker.java:46) ~[Medieval-Factions-4.5.1.jar:?]
        at dansplugins.factionsystem.eventhandlers.helper.RelationChecker.arePlayersInSameFaction(RelationChecker.java:26) ~[Medieval-Factions-4.5.1.jar:?]
        at dansplugins.factionsystem.eventhandlers.DamageHandler.handleIfFriendlyFire(DamageHandler.java:160) ~[Medieval-Factions-4.5.1.jar:?]
        at dansplugins.factionsystem.eventhandlers.DamageHandler.handlePlayerVersusPlayer(DamageHandler.java:52) ~[Medieval-Factions-4.5.1.jar:?]
        at dansplugins.factionsystem.eventhandlers.DamageHandler.handle(DamageHandler.java:39) ~[Medieval-Factions-4.5.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor218.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1547]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1161) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1010) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:963) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1195) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2122) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1056) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1383) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:963) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1062) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:409) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:225) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:216) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1219) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:698) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:676) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1639) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1501) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:51:43 ERROR]: Could not pass event EntityDamageByEntityEvent to MedievalFactions v4.5.1
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player1" is null
        at dansplugins.factionsystem.eventhandlers.helper.RelationChecker.getFactionIndices(RelationChecker.java:46) ~[Medieval-Factions-4.5.1.jar:?]
        at dansplugins.factionsystem.eventhandlers.helper.RelationChecker.arePlayersInSameFaction(RelationChecker.java:26) ~[Medieval-Factions-4.5.1.jar:?]
        at dansplugins.factionsystem.eventhandlers.DamageHandler.handleIfFriendlyFire(DamageHandler.java:160) ~[Medieval-Factions-4.5.1.jar:?]
        at dansplugins.factionsystem.eventhandlers.DamageHandler.handlePlayerVersusPlayer(DamageHandler.java:52) ~[Medieval-Factions-4.5.1.jar:?]
        at dansplugins.factionsystem.eventhandlers.DamageHandler.handle(DamageHandler.java:39) ~[Medieval-Factions-4.5.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor218.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1547]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1161) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1010) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:963) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1195) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2122) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1056) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1383) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:963) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1062) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:409) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:225) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:216) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1219) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:698) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:676) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1639) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1501) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

---
**Java version**
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [x] Java 17 
---
**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [x] v4.5.x
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [x] 1.18.x

**Comment by dmccoystephenson** [comment]
This issue should be fixed in this version:
https://github.com/dmccoystephenson/Medieval-Factions/releases/tag/v4.6-alpha-6

Please let me know if this is not the case.
